/** @vitest-environment jsdom */

// AI SDK seam tests: run the hook against the REAL
// `@ai-sdk/react` useChat and the REAL `DefaultChatTransport`, with `fetch`
// stubbed to serve a genuine v7 UI-message SSE stream (generated by the real
// server-side streamText → toUIMessageStream pipeline, so the wire format can
// never drift from the SDK). The sibling use-chat-core.test.tsx mocks
// @ai-sdk/react entirely, which is exactly why the v7 onFinish rename shipped
// unseen: a callback the SDK no longer invokes is invisible under a mock.
//
// The contract under test: useChat's `onFinish` drives
// chatTurn.finishChatTurn for ALL THREE turn outcomes — normal completion,
// stop() mid-stream (isAbort), and a transport error (isError).

import { resetSharedChatStreamOwnersForTests } from "./use-detachable-chat-stream"
import { clearLocallyResolvedApprovals } from "@/lib/chat-runs/approval-auto-send-gate"
import type { ModelReasoningEffort } from "@/lib/models/types"
import type { UserProfile } from "@/lib/user/types"
import type { UIMessage } from "@ai-sdk/react"
import {
  createUIMessageStreamResponse,
  jsonSchema,
  streamText,
  tool,
  toUIMessageStream,
} from "ai"
import { MockLanguageModelV4, simulateReadableStream } from "ai/test"
import React, { act } from "react"
import { createRoot, type Root } from "react-dom/client"
import {
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from "vitest"
import type { useChatCore as UseChatCore } from "./use-chat-core"

beforeEach(() => {
  // The shared stream owner is process-lived; without a reset, one test's
  // live mock binding leaks into the next test's mount-time readopt.
  resetSharedChatStreamOwnersForTests()
})

let useChatCore: typeof UseChatCore

const seamMocks = vi.hoisted(() => ({
  // Persistence is auth-derived (ADR-0033): guest scenarios flip this off.
  isAuthenticated: true,
  convexMutation: vi.fn(),
  updateTitle: vi.fn(),
  // Stable across renders so detached-finish persistence is observable: a
  // detached guest stream must cache into its ORIGIN chat id, never the
  // currently mounted one.
  cacheAndAddMessage: vi.fn(async (_message: unknown, _chatId?: string) => {}),
  turnSnapshotReasoningEffort: undefined as ModelReasoningEffort | undefined,
  controllerAdapters: null as null | {
    sendMessageAndWaitForAcceptance: (
      message: UIMessage & { messageId: string },
      options?: { body?: Record<string, unknown> }
    ) => Promise<void>
  },
  // The observation point for the seam: the controller the hook's onFinish
  // must invoke. A singleton, so whichever render's closure fires, the same
  // spies record it.
  chatTurnController: {
    runSendTurn: vi.fn(async (_args: unknown) => {}),
    runEditTurn: vi.fn(async (_args: unknown) => ({ status: "submitted" })),
    runRegenerationTurn: vi.fn(async (_args: unknown) => {}),
    finishChatTurn: vi.fn(async (_args: unknown) => {}),
  },
}))

// Only createChatTurnController (and types) are imported from this module in
// the hook's graph; a plain factory avoids loading the real controller chain.
vi.mock("@/lib/chat-turn/chat-turn-controller", () => ({
  createChatTurnController: (adapters: typeof seamMocks.controllerAdapters) => {
    seamMocks.controllerAdapters = adapters
    return seamMocks.chatTurnController
  },
}))

vi.mock("./turn-context", () => ({
  useTurnContext: () => ({
    selectedModel: "claude-haiku-4-5-20251001",
    handleModelChange: vi.fn(),
    enableSearch: false,
    setEnableSearch: vi.fn(),
    isAuthenticated: seamMocks.isAuthenticated,
    systemPrompt: "system prompt",
    isHydrated: true,
    getTurnSnapshot: () => ({
      selectedModel: "claude-haiku-4-5-20251001",
      systemPrompt: "system prompt",
      enableSearch: false,
      reasoningEffort: seamMocks.turnSnapshotReasoningEffort,
      isAuthenticated: seamMocks.isAuthenticated,
      isHydrated: true,
    }),
  }),
}))

vi.mock("@/convex/_generated/api", () => ({
  api: {
    chatRuntime: {
      approveToolCall: "approveToolCall",
      denyToolCall: "denyToolCall",
    },
  },
}))

vi.mock("convex/react", () => ({
  useMutation: () => seamMocks.convexMutation,
  useConvex: () => ({}),
  useConvexConnectionState: () => ({ isWebSocketConnected: true }),
}))

// The presentation resolver's durable input: guest/local default (no run).
vi.mock("@/lib/chat-store/messages/provider", () => ({
  useMessages: () => ({ selectedRun: null }),
}))

vi.mock("next/navigation", () => ({
  useSearchParams: () => new URLSearchParams(window.location.search),
}))

vi.mock("@/components/ui/toast", () => ({
  toast: vi.fn(),
}))

vi.mock("@/lib/api", () => ({
  getOrCreateGuestUserId: vi.fn(async () => "user-1"),
}))

vi.mock("@/lib/chat-store/chats/provider", () => ({
  useChats: () => ({
    updateTitle: seamMocks.updateTitle,
  }),
}))

const CHAT_ID = "chat-seam"

const authenticatedUser = {
  id: "user-1",
  email: "user@example.com",
  display_name: "User",
  profile_image: null,
  anonymous: false,
  premium: true,
  message_count: 0,
  daily_message_count: 0,
  daily_reset: null,
  last_active_at: null,
  created_at: null,
  favorite_models: null,
  system_prompt: "system prompt",
} as unknown as UserProfile

const STEP_USAGE = {
  inputTokens: {
    total: 7,
    noCache: 7,
    cacheRead: undefined,
    cacheWrite: undefined,
  },
  outputTokens: { total: 3, text: 3, reasoning: undefined },
}

/**
 * Build a real v7 UI-message SSE Response by running the genuine server-side
 * pipeline over a mock provider model. `chunkDelayInMs` keeps the stream open
 * long enough for stop() to land mid-stream.
 */
function makeUiMessageSseResponse(options: {
  deltas: string[]
  chunkDelayInMs: number | null
}) {
  const result = streamText({
    model: new MockLanguageModelV4({
      doStream: async () => ({
        stream: simulateReadableStream({
          chunks: [
            { type: "stream-start" as const, warnings: [] },
            { type: "text-start" as const, id: "t1" },
            ...options.deltas.map((delta) => ({
              type: "text-delta" as const,
              id: "t1",
              delta,
            })),
            { type: "text-end" as const, id: "t1" },
            {
              type: "finish" as const,
              finishReason: { unified: "stop" as const, raw: "end_turn" },
              usage: STEP_USAGE,
            },
          ],
          chunkDelayInMs: options.chunkDelayInMs,
        }),
      }),
    }),
    prompt: "hi",
  })
  return createUIMessageStreamResponse({
    stream: toUIMessageStream({ stream: result.stream }),
  })
}

function makePartialUiMessageErrorResponse(partialText: string): Response {
  const encoder = new TextEncoder()
  const records = [
    { type: "start", messageId: "partial-error-message" },
    { type: "text-start", id: "partial-error-text" },
    {
      type: "text-delta",
      id: "partial-error-text",
      delta: partialText,
    },
  ]
  return new Response(
    new ReadableStream<Uint8Array>({
      start(controller) {
        controller.enqueue(
          encoder.encode(
            records
              .map((record) => `data: ${JSON.stringify(record)}\n\n`)
              .join("")
          )
        )
        setTimeout(() => controller.error(new Error("stream failed")), 1)
      },
    }),
    {
      headers: {
        "content-type": "text/event-stream",
        "x-vercel-ai-ui-message-stream": "v1",
      },
    }
  )
}

/**
 * Mirror real fetch abort semantics for the stubbed response: when the
 * transport's request signal aborts, the body reader must reject with an
 * AbortError — that is the signal path useChat's stop() relies on.
 */
function withAbortSemantics(
  response: Response,
  signal: AbortSignal | null | undefined,
  onDone?: () => void
): Response {
  if (!response.body) return response
  const reader = response.body.getReader()
  const body = new ReadableStream<Uint8Array>({
    start(controller) {
      if (!signal) return
      const onAbort = () => {
        controller.error(
          new DOMException("The operation was aborted.", "AbortError")
        )
        void reader.cancel().catch(() => {})
      }
      if (signal.aborted) onAbort()
      else signal.addEventListener("abort", onAbort, { once: true })
    },
    async pull(controller) {
      const { done, value } = await reader.read()
      if (done) {
        controller.close()
        onDone?.()
      } else controller.enqueue(value)
    },
    cancel() {
      void reader.cancel().catch(() => {})
    },
  })
  return new Response(body, {
    status: response.status,
    headers: response.headers,
  })
}

type HookApi = ReturnType<typeof UseChatCore>

describe("useChatCore × real @ai-sdk/react finalization", () => {
  let container: HTMLDivElement | null = null
  let root: Root | null = null
  const hookApiRef: { current: HookApi | null } = { current: null }
  const fetchMock = vi.fn<typeof fetch>()

  beforeAll(async () => {
    ;(
      globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }
    ).IS_REACT_ACT_ENVIRONMENT = true
    // lib/chat-store/persist touches indexedDB at module scope — shim it
    // before the hook module (and its chat-store chain) loads.
    const objectStoreNames = Object.assign(["chats", "messages", "sync"], {
      contains: (name: string) => ["chats", "messages", "sync"].includes(name),
    })
    const db = {
      version: 2,
      objectStoreNames,
      close: vi.fn(),
      createObjectStore: vi.fn(),
    }
    ;(globalThis as { indexedDB?: IDBFactory }).indexedDB = {
      open: vi.fn(() => {
        const request = {
          result: db,
          error: null,
        } as unknown as IDBOpenDBRequest
        window.setTimeout(() => request.onsuccess?.(new Event("success")), 0)
        return request
      }),
      deleteDatabase: vi.fn(() => {
        const request = { result: undefined } as unknown as IDBOpenDBRequest
        window.setTimeout(() => request.onsuccess?.(new Event("success")), 0)
        return request
      }),
    } as unknown as IDBFactory
    ;({ useChatCore } = await import("./use-chat-core"))
  })

  beforeEach(() => {
    vi.clearAllMocks()
    seamMocks.turnSnapshotReasoningEffort = undefined
    seamMocks.isAuthenticated = true
    vi.stubGlobal("requestAnimationFrame", (callback: FrameRequestCallback) =>
      window.setTimeout(() => callback(performance.now()), 16)
    )
    vi.stubGlobal("cancelAnimationFrame", (id: number) =>
      window.clearTimeout(id)
    )
    vi.stubGlobal("fetch", fetchMock)
    window.history.replaceState(null, "", `/c/${CHAT_ID}`)
  })

  afterEach(() => {
    vi.unstubAllGlobals()
    const mountedRoot = root
    if (mountedRoot) {
      act(() => {
        mountedRoot.unmount()
      })
    }
    container?.remove()
    container = null
    root = null
    hookApiRef.current = null
  })

  // Lets a test drive a mounted chat-id transition (shallow-pushState Back to
  // the onboarding surface) without remounting the Harness.
  const setChatIdRef: { current: ((chatId: string | null) => void) | null } = {
    current: null,
  }

  // Delivered-message-notification recorder: one entry per render
  // in which React observed a NEW messages array identity — the exact seam the
  // frame subscription batches. `atMs` is the virtual clock at delivery.
  type MessagesFrame = { messages: UIMessage[]; status: string; atMs: number }
  const framesRecorder: { current: MessagesFrame[] | null } = { current: null }

  function Harness({ initialChatId }: { initialChatId: string | null }) {
    const [chatId, setChatId] = React.useState<string | null>(initialChatId)
    React.useEffect(() => {
      setChatIdRef.current = setChatId
    }, [])
    const api = useChatCore({
      initialMessages: [] as UIMessage[],
      cacheAndAddMessage: seamMocks.cacheAndAddMessage,
      chatId,
      user: authenticatedUser,
      isChatAdmissionReady: true,
      checkLimitsAndNotify: vi.fn(async () => true),
      firstTurn: { begin: () => "chat-1", rollback: () => {} },
      ensureChatExists: vi.fn(async () => ({ chatId: CHAT_ID })),
      bumpChat: vi.fn(),
    })
    // Per-commit frame recording (no dep array): one entry per commit whose
    // messages identity changed — the delivered-notification count.
    React.useEffect(() => {
      const frames = framesRecorder.current
      if (frames && frames[frames.length - 1]?.messages !== api.messages) {
        frames.push({
          messages: api.messages,
          status: api.status,
          atMs: Date.now(),
        })
      }
    })
    React.useEffect(() => {
      hookApiRef.current = api
    })
    return null
  }

  function renderHook(initialChatId: string | null = CHAT_ID): HookApi {
    container = document.createElement("div")
    document.body.appendChild(container)
    root = createRoot(container)
    act(() => {
      root?.render(<Harness initialChatId={initialChatId} />)
    })
    const api = hookApiRef.current
    if (!api) throw new Error("useChatCore did not render")
    return api
  }

  /** Poll an assertion while flushing React work inside act(). */
  async function waitForInAct(assertion: () => void, timeoutMs = 4000) {
    const start = Date.now()
    for (;;) {
      try {
        assertion()
        return
      } catch (error) {
        if (Date.now() - start > timeoutMs) throw error
        await act(async () => {
          await new Promise((resolve) => setTimeout(resolve, 20))
        })
      }
    }
  }

  it("finishes a normal turn through finishChatTurn with clean flags", async () => {
    fetchMock.mockImplementation(async (_url, init) =>
      withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: ["Hello ", "world."],
          chunkDelayInMs: null,
        }),
        init?.signal
      )
    )
    const hook = renderHook()

    await act(async () => {
      await hook.sendMessage({ text: "hi" })
    })

    const finish = seamMocks.chatTurnController.finishChatTurn
    await waitForInAct(() => expect(finish).toHaveBeenCalledTimes(1))
    const args = finish.mock.calls[0][0] as Record<string, unknown>
    expect(args).toMatchObject({
      isAbort: false,
      isDisconnect: false,
      isError: false,
      chatId: CHAT_ID,
    })
    expect(args.finishReason).toBe("stop")
    const message = args.message as UIMessage
    expect(message.role).toBe("assistant")
    expect(
      message.parts
        .filter((part) => part.type === "text")
        .map((part) => (part as { text: string }).text)
        .join("")
    ).toBe("Hello world.")
  })

  it("finishes a stopped turn with isAbort after stop() mid-stream", async () => {
    fetchMock.mockImplementation(async (_url, init) =>
      withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: Array.from({ length: 10 }, (_, i) => `piece-${i} `),
          chunkDelayInMs: 25,
        }),
        init?.signal
      )
    )
    const hook = renderHook()

    await act(async () => {
      void hook.sendMessage({ text: "hi" })
    })
    await waitForInAct(() =>
      expect(hookApiRef.current?.status).toBe("streaming")
    )

    await act(async () => {
      await hookApiRef.current?.stop()
    })

    const finish = seamMocks.chatTurnController.finishChatTurn
    await waitForInAct(() => expect(finish).toHaveBeenCalledTimes(1))
    expect(finish.mock.calls[0][0]).toMatchObject({
      isAbort: true,
      isError: false,
      chatId: CHAT_ID,
    })
  })

  it("detaches (no abort) on a mounted transition to the onboarding surface", async () => {
    // Durable chat: the detached stream must neither abort nor produce ANY
    // client-side finish work — persistence is server-owned (ADR-0011).
    const requestSignals: (AbortSignal | null | undefined)[] = []
    let resolveStreamServed!: () => void
    const streamServed = new Promise<void>((resolve) => {
      resolveStreamServed = resolve
    })
    fetchMock.mockImplementation(async (_url, init) => {
      requestSignals.push(init?.signal)
      return withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: Array.from({ length: 10 }, (_, i) => `piece-${i} `),
          chunkDelayInMs: 25,
        }),
        init?.signal,
        resolveStreamServed
      )
    })
    const hook = renderHook()

    await act(async () => {
      void hook.sendMessage({ text: "hi" })
    })
    await waitForInAct(() =>
      expect(hookApiRef.current?.status).toBe("streaming")
    )

    // Browser Back over the shallow-pushState first-turn flow: Chat stays
    // mounted, chatId drops to null in place.
    await act(async () => {
      setChatIdRef.current?.(null)
    })

    // Detached, not aborted: the request signal stays live and the mounted
    // thread is empty (showOnboarding requires messages.length === 0).
    expect(requestSignals[0]?.aborted).toBe(false)
    expect(hookApiRef.current?.messages).toEqual([])
    expect(hookApiRef.current?.status).toBe("ready")

    // Run the detached stream to completion INSIDE this test (no cross-test
    // leakage), then flush its finish handling.
    await act(async () => {
      await streamServed
    })
    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 50))
    })

    // A detached durable finish is a client no-op: no attached finish, no
    // client persistence, no deltas leaked into the mounted array.
    expect(requestSignals[0]?.aborted).toBe(false)
    expect(seamMocks.chatTurnController.finishChatTurn).not.toHaveBeenCalled()
    expect(seamMocks.cacheAndAddMessage).not.toHaveBeenCalled()
    expect(hookApiRef.current?.messages).toEqual([])
  })

  it("persists a detached guest stream into its origin chat, not the current one", async () => {
    seamMocks.isAuthenticated = false
    // The origin-binding contract: after a mounted A→B transition, the
    // detached guest stream's assistant message caches under chat A (the
    // binding's frozen ownerChatId), never under B or via stored-guest-id
    // fallbacks.
    const originChatId = "local-detach-origin"
    const nextChatId = "local-detach-next"
    const expectedText = Array.from({ length: 10 }, (_, i) => `piece-${i} `)
    fetchMock.mockImplementation(async (_url, init) =>
      withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: expectedText,
          chunkDelayInMs: 25,
        }),
        init?.signal
      )
    )
    const hook = renderHook(originChatId)

    await act(async () => {
      void hook.sendMessage({ text: "hi" })
    })
    await waitForInAct(() =>
      expect(hookApiRef.current?.status).toBe("streaming")
    )

    // Mounted transition to ANOTHER chat while the stream is live.
    await act(async () => {
      setChatIdRef.current?.(nextChatId)
    })
    expect(hookApiRef.current?.messages).toEqual([])

    // The detached finish caches the full assistant message under the ORIGIN
    // chat, and never routes through the attached finish path.
    await waitForInAct(() =>
      expect(seamMocks.cacheAndAddMessage).toHaveBeenCalledTimes(1)
    )
    const [cachedMessage, cachedChatId] =
      seamMocks.cacheAndAddMessage.mock.calls[0]
    expect(cachedChatId).toBe(originChatId)
    const message = cachedMessage as UIMessage
    expect(message.role).toBe("assistant")
    expect(
      message.parts
        .filter((part) => part.type === "text")
        .map((part) => (part as { text: string }).text)
        .join("")
    ).toBe(expectedText.join(""))
    expect(seamMocks.chatTurnController.finishChatTurn).not.toHaveBeenCalled()
    expect(hookApiRef.current?.messages).toEqual([])
  })

  it("still aborts through the Stop button after a detach recreated the instance", async () => {
    seamMocks.isAuthenticated = false
    // Regression guard for the Stop chain (Stop → req.signal → onAbort): the
    // stop() handed out after a detach must abort the CURRENT instance's
    // stream, and only that stream.
    const originChatId = "local-stop-origin"
    const requestSignals: (AbortSignal | null | undefined)[] = []
    fetchMock.mockImplementation(async (_url, init) => {
      requestSignals.push(init?.signal)
      return withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: Array.from({ length: 10 }, (_, i) => `piece-${i} `),
          chunkDelayInMs: 25,
        }),
        init?.signal
      )
    })
    const hook = renderHook(originChatId)

    await act(async () => {
      void hook.sendMessage({ text: "hi" })
    })
    await waitForInAct(() =>
      expect(hookApiRef.current?.status).toBe("streaming")
    )

    // Detach (Back to onboarding), then start a new turn on the fresh
    // instance and Stop it mid-stream.
    await act(async () => {
      setChatIdRef.current?.(null)
    })
    await act(async () => {
      void hookApiRef.current?.sendMessage({ text: "hi again" })
    })
    await waitForInAct(() =>
      expect(hookApiRef.current?.status).toBe("streaming")
    )
    await act(async () => {
      await hookApiRef.current?.stop()
    })

    // The new turn aborted through the attached finish path; the detached
    // stream was never aborted.
    expect(requestSignals[1]?.aborted).toBe(true)
    expect(requestSignals[0]?.aborted).toBe(false)
    const finish = seamMocks.chatTurnController.finishChatTurn
    await waitForInAct(() =>
      expect(
        finish.mock.calls.some(
          (call) => (call[0] as { isAbort: boolean }).isAbort
        )
      ).toBe(true)
    )

    // Run the detached guest stream to completion inside this test: it caches
    // under its origin chat, unaffected by the Stop.
    await waitForInAct(() =>
      expect(seamMocks.cacheAndAddMessage).toHaveBeenCalledWith(
        expect.objectContaining({ role: "assistant" }),
        originChatId
      )
    )
    expect(requestSignals[0]?.aborted).toBe(false)
  })

  it("re-adopts the still-live origin stream on return, resuming the word-granular local array", async () => {
    // A → B → A mid-stream must restore the original live binding instead of
    // a fresh binding fed by
    // 750 ms durable snapshots. The finish then routes through the ATTACHED
    // path with the origin identity, not the detached guest-cache path.
    const originChatId = "local-readopt-origin"
    const nextChatId = "local-readopt-next"
    const expectedText = Array.from({ length: 10 }, (_, i) => `piece-${i} `)
    const requestSignals: (AbortSignal | null | undefined)[] = []
    fetchMock.mockImplementation(async (_url, init) => {
      requestSignals.push(init?.signal)
      return withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: expectedText,
          chunkDelayInMs: 25,
        }),
        init?.signal
      )
    })
    const hook = renderHook(originChatId)

    await act(async () => {
      void hook.sendMessage({ text: "hi" })
    })
    await waitForInAct(() =>
      expect(hookApiRef.current?.status).toBe("streaming")
    )

    // Away mid-stream: the mounted surface empties (detach, no abort)…
    await act(async () => {
      setChatIdRef.current?.(nextChatId)
    })
    expect(hookApiRef.current?.messages).toEqual([])
    expect(hookApiRef.current?.status).toBe("ready")

    // …and return re-adopts: the surface is streaming again with the origin
    // chat's canonical array, not an empty fresh binding.
    await act(async () => {
      setChatIdRef.current?.(originChatId)
    })
    await waitForInAct(() => {
      expect(hookApiRef.current?.status).toBe("streaming")
      expect(
        hookApiRef.current?.messages.some(
          (message) => message.role === "assistant"
        )
      ).toBe(true)
    })

    // Completion routes through the attached finish with the origin identity.
    const finish = seamMocks.chatTurnController.finishChatTurn
    await waitForInAct(() => expect(finish).toHaveBeenCalledTimes(1))
    expect(finish.mock.calls[0][0]).toMatchObject({
      isAbort: false,
      isDisconnect: false,
      isError: false,
      chatId: originChatId,
    })
    const message = (finish.mock.calls[0][0] as { message: UIMessage }).message
    expect(
      message.parts
        .filter((part) => part.type === "text")
        .map((part) => (part as { text: string }).text)
        .join("")
    ).toBe(expectedText.join(""))
    // Never aborted, and the detached guest-cache path never ran.
    expect(requestSignals[0]?.aborted).toBe(false)
    expect(seamMocks.cacheAndAddMessage).not.toHaveBeenCalled()
    // The mounted array carries the fully streamed assistant text.
    await waitForInAct(() =>
      expect(
        hookApiRef.current?.messages
          .filter((m) => m.role === "assistant")
          .flatMap((m) => m.parts)
          .filter((part) => part.type === "text")
          .map((part) => (part as { text: string }).text)
          .join("")
      ).toBe(expectedText.join(""))
    )
  })

  it("finishes an errored turn with isError when the transport fails", async () => {
    fetchMock.mockImplementation(
      async () => new Response("model exploded", { status: 500 })
    )
    const hook = renderHook()

    await act(async () => {
      await hook.sendMessage({ text: "hi" })
    })

    const finish = seamMocks.chatTurnController.finishChatTurn
    await waitForInAct(() => expect(finish).toHaveBeenCalledTimes(1))
    expect(finish.mock.calls[0][0]).toMatchObject({
      isAbort: false,
      isError: true,
      chatId: CHAT_ID,
    })
    await waitForInAct(() => expect(hookApiRef.current?.status).toBe("error"))
  })

  it("rejects request acceptance on an asynchronous HTTP failure", async () => {
    fetchMock.mockImplementation(
      async () => new Response("prepare failed", { status: 503 })
    )
    const hook = renderHook()
    const optimistic = {
      id: "first-turn-client-id",
      role: "user" as const,
      parts: [{ type: "text" as const, text: "hi" }],
      messageId: "first-turn-client-id",
    }
    act(() => hook.setMessages([optimistic]))

    const acceptance =
      seamMocks.controllerAdapters?.sendMessageAndWaitForAcceptance(
        optimistic,
        {
          body: { chatId: CHAT_ID },
        }
      )
    if (!acceptance) throw new Error("controller adapters were not captured")

    await expect(acceptance).rejects.toThrow("prepare failed")
    // AI SDK catches the transport error for chat state; the explicit
    // acceptance promise still rejects, so the controller can retain identity.
    await waitForInAct(() => expect(hookApiRef.current?.status).toBe("error"))
  })

  it("acknowledges an accepted request before the response stream completes", async () => {
    fetchMock.mockImplementation(async (_url, init) =>
      withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: Array.from({ length: 10 }, (_, index) => `piece-${index} `),
          chunkDelayInMs: 25,
        }),
        init?.signal
      )
    )
    const hook = renderHook()
    const optimistic = {
      id: "accepted-first-turn-id",
      role: "user" as const,
      parts: [{ type: "text" as const, text: "hi" }],
      messageId: "accepted-first-turn-id",
    }
    act(() => hook.setMessages([optimistic]))

    const acceptance =
      seamMocks.controllerAdapters?.sendMessageAndWaitForAcceptance(
        optimistic,
        {
          body: { chatId: CHAT_ID },
        }
      )
    if (!acceptance) throw new Error("controller adapters were not captured")

    await expect(acceptance).resolves.toBeUndefined()
    expect(seamMocks.chatTurnController.finishChatTurn).not.toHaveBeenCalled()

    // Keep the open stream inside this test; Stop remains the explicit
    // cancellation path after acceptance.
    await act(async () => {
      await hook.stop()
    })
    await waitForInAct(() =>
      expect(seamMocks.chatTurnController.finishChatTurn).toHaveBeenCalled()
    )
  })

  // Frame-aligned message publication.
  //
  // AI SDK's Chat remains canonical per stream part. The adapter publishes
  // that latest snapshot once per paint while status/error, onFinish, Stop,
  // approvals, and auto-send continuation stay immediate. All timers are fake,
  // so delivery counts and times are exact virtual-clock facts.
  describe("frame-aligned message publication", () => {
    beforeEach(() => {
      vi.useFakeTimers({
        toFake: [
          "setTimeout",
          "clearTimeout",
          "setInterval",
          "clearInterval",
          "Date",
        ],
      })
      clearLocallyResolvedApprovals()
    })

    afterEach(() => {
      vi.useRealTimers()
      framesRecorder.current = null
    })

    /** Local mount that a test can unmount mid-test (matrix runs, remounts). */
    function mountFrameHarness() {
      const localContainer = document.createElement("div")
      document.body.appendChild(localContainer)
      const localRoot = createRoot(localContainer)
      act(() => {
        localRoot.render(<Harness initialChatId={CHAT_ID} />)
      })
      if (!hookApiRef.current) throw new Error("useChatCore did not render")
      return {
        unmount: () => {
          act(() => {
            localRoot.unmount()
          })
          localContainer.remove()
        },
      }
    }

    async function advanceFake(ms: number) {
      await act(async () => {
        await vi.advanceTimersByTimeAsync(ms)
      })
    }

    /** Poll an assertion while advancing the fake clock in small steps. */
    async function waitFake(
      assertion: () => void,
      { stepMs = 10, maxSteps = 300 } = {}
    ) {
      for (let step = 0; ; step++) {
        try {
          assertion()
          return
        } catch (error) {
          if (step >= maxSteps) throw error
          await advanceFake(stepMs)
        }
      }
    }

    function assistantText(messages: UIMessage[]): string {
      const assistant = [...messages]
        .reverse()
        .find((message) => message.role === "assistant")
      if (!assistant) return ""
      return assistant.parts
        .filter((part) => part.type === "text")
        .map((part) => (part as { text: string }).text)
        .join("")
    }

    /** Strips per-run random identifiers so finals can be deep-compared. */
    function normalizeMessage(message: UIMessage): unknown {
      const volatileKeys = new Set([
        "id",
        "toolCallId",
        "messageId",
        "createdAt",
      ])
      return JSON.parse(
        JSON.stringify(message, (key, value) =>
          volatileKeys.has(key) ? "<volatile>" : value
        )
      )
    }

    it("coalesces a high-cadence stream to paint frames and delivers the identical final message", async () => {
      const deltas = Array.from({ length: 60 }, (_, i) => `piece-${i} `)
      fetchMock.mockImplementation(async (_url, init) =>
        withAbortSemantics(
          makeUiMessageSseResponse({
            deltas,
            chunkDelayInMs: 1,
          }),
          init?.signal
        )
      )
      framesRecorder.current = []
      const mounted = mountFrameHarness()
      const startedAtMs = Date.now()

      await act(async () => {
        void hookApiRef.current?.sendMessage({ text: "hi" })
      })
      await advanceFake(250)

      const finish = seamMocks.chatTurnController.finishChatTurn
      expect(finish).toHaveBeenCalledTimes(1)
      const finishMessage = (finish.mock.calls[0][0] as { message: UIMessage })
        .message
      const frames = framesRecorder.current
      if (!frames) throw new Error("frames recorder was not installed")
      const lastFrame = frames[frames.length - 1]
      const renderedAssistant = [...lastFrame.messages]
        .reverse()
        .find((message) => message.role === "assistant")
      if (!renderedAssistant) throw new Error("assistant frame missing")

      expect(assistantText(lastFrame.messages)).toBe(deltas.join(""))
      expect(normalizeMessage(renderedAssistant)).toEqual(
        normalizeMessage(finishMessage)
      )
      expect(frames.length).toBeLessThan(deltas.length / 2)

      const firstTextFrame = frames.find(
        (frame) => assistantText(frame.messages).length > 0
      )
      if (!firstTextFrame) throw new Error("first text frame missing")
      expect(firstTextFrame.atMs - startedAtMs).toBeLessThanOrEqual(32)

      const streamingTextFrames = frames.filter(
        (frame) =>
          frame.status === "streaming" &&
          assistantText(frame.messages).length > 0
      )
      for (let index = 1; index < streamingTextFrames.length; index++) {
        expect(
          streamingTextFrames[index].atMs - streamingTextFrames[index - 1].atMs
        ).toBeGreaterThanOrEqual(16)
      }
      mounted.unmount()
    })

    it("keeps status and error subscriptions immediate between paints", async () => {
      // (a) Status flips to "streaming" before the next frame publication.
      fetchMock.mockImplementation(async (_url, init) =>
        withAbortSemantics(
          makeUiMessageSseResponse({
            deltas: Array.from({ length: 10 }, (_, i) => `piece-${i} `),
            chunkDelayInMs: 10,
          }),
          init?.signal
        )
      )
      framesRecorder.current = []
      const mounted = mountFrameHarness()
      await act(async () => {
        void hookApiRef.current?.sendMessage({ text: "hi" })
      })
      await advanceFake(25)
      expect(hookApiRef.current?.status).toBe("streaming")
      await advanceFake(300)
      expect(hookApiRef.current?.status).toBe("ready")
      expect(seamMocks.chatTurnController.finishChatTurn).toHaveBeenCalledTimes(
        1
      )
      mounted.unmount()
      seamMocks.chatTurnController.finishChatTurn.mockClear()

      // (b) A transport error surfaces without any timer advance: the error
      // subscription is not frame-coalesced.
      fetchMock.mockImplementation(
        async () => new Response("model exploded", { status: 500 })
      )
      const errorMount = mountFrameHarness()
      await act(async () => {
        void hookApiRef.current?.sendMessage({ text: "hi" })
      })
      await waitFake(() => expect(hookApiRef.current?.status).toBe("error"), {
        stepMs: 5,
        maxSteps: 10,
      })
      await waitFake(() =>
        expect(
          seamMocks.chatTurnController.finishChatTurn
        ).toHaveBeenCalledWith(expect.objectContaining({ isError: true }))
      )
      errorMount.unmount()
    })

    it("terminal status flushes the latest canonical snapshot before the pending frame", async () => {
      const finalText = "terminal snapshot"
      fetchMock.mockImplementation(async (_url, init) =>
        withAbortSemantics(
          makeUiMessageSseResponse({
            deltas: ["terminal ", "snapshot"],
            chunkDelayInMs: null,
          }),
          init?.signal
        )
      )
      framesRecorder.current = []
      const mounted = mountFrameHarness()

      await act(async () => {
        void hookApiRef.current?.sendMessage({ text: "hi" })
      })
      // simulateReadableStream schedules its null-delay chunks at 0 ms. Flush
      // those without crossing the pending frame publication.
      await advanceFake(0)

      // No timer advance: the immediate status transition causes React to
      // re-read the current message snapshot through useSyncExternalStore.
      expect(hookApiRef.current?.status).toBe("ready")
      const frames = framesRecorder.current
      if (!frames) throw new Error("frames recorder was not installed")
      const terminalFrame = [...frames]
        .reverse()
        .find((frame) => frame.status === "ready")
      expect(assistantText(terminalFrame?.messages ?? [])).toBe(finalText)

      const frameCountBeforeTrailingTimer = frames.length
      await advanceFake(16)
      expect(frames.length).toBe(frameCountBeforeTrailingTimer)
      expect(assistantText(hookApiRef.current?.messages ?? [])).toBe(finalText)
      mounted.unmount()
    })

    it("transport error flushes delivered partial text before the pending frame", async () => {
      const partialText = "delivered partial"
      fetchMock.mockImplementation(async () =>
        makePartialUiMessageErrorResponse(partialText)
      )
      framesRecorder.current = []
      const mounted = mountFrameHarness()

      await act(async () => {
        void hookApiRef.current?.sendMessage({ text: "hi" })
      })
      await advanceFake(1)

      expect(hookApiRef.current?.status).toBe("error")
      const frames = framesRecorder.current
      if (!frames) throw new Error("frames recorder was not installed")
      const errorFrame = [...frames]
        .reverse()
        .find((frame) => frame.status === "error")
      expect(assistantText(errorFrame?.messages ?? [])).toBe(partialText)
      expect(assistantText(hookApiRef.current?.messages ?? [])).toBe(
        partialText
      )
      mounted.unmount()
    })

    it("Stop mid-stream settles isAbort and synchronously preserves the exact partial output", async () => {
      fetchMock.mockImplementation(async (_url, init) =>
        withAbortSemantics(
          makeUiMessageSseResponse({
            deltas: Array.from({ length: 20 }, (_, i) => `piece-${i} `),
            chunkDelayInMs: 25,
          }),
          init?.signal
        )
      )
      framesRecorder.current = []
      const mounted = mountFrameHarness()
      await act(async () => {
        void hookApiRef.current?.sendMessage({ text: "hi" })
      })
      await waitFake(() => expect(hookApiRef.current?.status).toBe("streaming"))
      await advanceFake(80)
      await act(async () => {
        await hookApiRef.current?.stop()
      })
      await waitFake(() =>
        expect(
          seamMocks.chatTurnController.finishChatTurn
        ).toHaveBeenCalledWith(expect.objectContaining({ isAbort: true }))
      )
      const finishArgs = seamMocks.chatTurnController.finishChatTurn.mock
        .calls[0][0] as { message: UIMessage }
      const partialText = assistantText([finishArgs.message])
      expect(partialText.length).toBeGreaterThan(0)
      expect(deltas20Text().startsWith(partialText)).toBe(true)

      const frames = framesRecorder.current
      if (!frames) throw new Error("frames recorder was not installed")
      // Before advancing the pending notification window, the immediate
      // terminal status render already reads the exact partial snapshot.
      expect(assistantText(frames[frames.length - 1].messages)).toBe(
        partialText
      )
      const settledFrameCount = frames.length
      await advanceFake(150)
      await advanceFake(400)
      expect(frames.length).toBe(settledFrameCount)
      mounted.unmount()

      function deltas20Text() {
        return Array.from({ length: 20 }, (_, i) => `piece-${i} `).join("")
      }
    })

    it.each([
      ["high", "low"],
      [undefined, "high"],
    ] as const)(
      "tool approval preserves paused effort %s through its one-shot continuation",
      async (pausedEffort, nextTurnEffort) => {
        seamMocks.convexMutation.mockResolvedValue({
          status: "approved",
          alreadyResolved: false,
          reason: undefined,
        })

        // Request 1: a real needsApproval tool-call turn built by the genuine
        // server pipeline; request 2: the continuation's text answer.
        const makeApprovalSseResponse = () => {
          const result = streamText({
            model: new MockLanguageModelV4({
              doStream: async () => ({
                stream: simulateReadableStream({
                  chunks: [
                    { type: "stream-start" as const, warnings: [] },
                    {
                      type: "tool-call" as const,
                      toolCallId: "call-approve-1",
                      toolName: "send_note",
                      input: JSON.stringify({ note: "hello" }),
                    },
                    {
                      type: "finish" as const,
                      finishReason: {
                        unified: "tool-calls" as const,
                        raw: "tool_use",
                      },
                      usage: STEP_USAGE,
                    },
                  ],
                  chunkDelayInMs: null,
                }),
              }),
            }),
            tools: {
              send_note: tool({
                description: "Send a note",
                inputSchema: jsonSchema<{ note: string }>({
                  type: "object",
                  properties: { note: { type: "string" } },
                  required: ["note"],
                  additionalProperties: false,
                }),
                needsApproval: true,
                execute: async () => ({ ok: true }),
              }),
            },
            prompt: "hi",
          })
          return createUIMessageStreamResponse({
            stream: toUIMessageStream({
              stream: result.stream,
              messageMetadata: () => ({
                generationBudget: 16_384,
                ...(pausedEffort === undefined
                  ? {}
                  : { reasoningEffort: pausedEffort }),
              }),
            }),
          })
        }

        let requestCount = 0
        fetchMock.mockImplementation(async (_url, init) => {
          requestCount += 1
          return withAbortSemantics(
            requestCount === 1
              ? makeApprovalSseResponse()
              : makeUiMessageSseResponse({
                  deltas: ["Continued ", "answer."],
                  chunkDelayInMs: null,
                }),
            init?.signal
          )
        })

        framesRecorder.current = []
        const mounted = mountFrameHarness()
        seamMocks.turnSnapshotReasoningEffort = pausedEffort
        await act(async () => {
          void hookApiRef.current?.sendMessage({ text: "hi" })
        })
        await advanceFake(0)

        // The approval terminal render must expose the latest tool part before
        // the pending frame publication is advanced.
        type ApprovalToolPart = {
          type: string
          state?: string
          approval?: { id?: string; approved?: boolean }
        }
        const findToolPart = (): ApprovalToolPart | undefined => {
          const messages = hookApiRef.current?.messages ?? []
          const assistant = [...messages]
            .reverse()
            .find((message) => message.role === "assistant")
          return assistant?.parts.find(
            (part) => part.type === "tool-send_note"
          ) as ApprovalToolPart | undefined
        }
        expect(hookApiRef.current?.status).toBe("ready")
        expect(findToolPart()?.state).toBe("approval-requested")
        const approvalId = findToolPart()?.approval?.id
        if (!approvalId) throw new Error("approval id missing from tool part")

        // Composer changes during the pause belong to the next user turn.
        seamMocks.turnSnapshotReasoningEffort = nextTurnEffort
        await act(async () => {
          await hookApiRef.current?.handleToolApproval(approvalId, true)
        })
        // The approval response and the continuation dispatch are not lost to
        // frame coalescing: exactly one second request, and the continuation's
        // answer lands in the rendered conversation.
        await waitFake(() => expect(fetchMock).toHaveBeenCalledTimes(2))
        await waitFake(() =>
          expect(assistantText(hookApiRef.current?.messages ?? [])).toContain(
            "Continued answer."
          )
        )
        expect(findToolPart()?.state).toBe("approval-responded")
        expect(findToolPart()?.approval?.approved).toBe(true)
        const continuationInit = fetchMock.mock.calls[1]?.[1]
        if (typeof continuationInit?.body !== "string") {
          throw new Error("continuation request body missing")
        }
        expect(JSON.parse(continuationInit.body).reasoningEffort).toBe(
          pausedEffort
        )
        expect(JSON.parse(continuationInit.body).generationBudget).toBe(16_384)

        // One-shot: no further dispatches however long the clock runs.
        await advanceFake(500)
        expect(fetchMock).toHaveBeenCalledTimes(2)
        mounted.unmount()
      }
    )

    it("survives unmount during a pending trailing update", async () => {
      // Unmount while a trailing notification is still scheduled: the late
      // timer must be inert (no throw, no state corruption), and a fresh
      // mount starts clean.
      fetchMock.mockImplementation(async (_url, init) =>
        withAbortSemantics(
          makeUiMessageSseResponse({
            deltas: ["fast ", "stream."],
            chunkDelayInMs: 5,
          }),
          init?.signal
        )
      )
      framesRecorder.current = []
      const secondMount = mountFrameHarness()
      await act(async () => {
        void hookApiRef.current?.sendMessage({ text: "hi" })
      })
      await advanceFake(30) // stream done; trailing update still pending
      secondMount.unmount()
      await advanceFake(500) // fire the orphaned trailing timer

      framesRecorder.current = null
      const remount = mountFrameHarness()
      expect(hookApiRef.current?.status).toBe("ready")
      expect(hookApiRef.current?.messages).toEqual([])
      remount.unmount()
    })
  })
})
