/** @vitest-environment jsdom */

// ---------------------------------------------------------------------------
// AI SDK seam tests (PR #97 regression class): run the hook against the REAL
// `@ai-sdk/react` useChat and the REAL `DefaultChatTransport`, with `fetch`
// stubbed to serve a genuine v7 UI-message SSE stream (generated by the real
// server-side streamText → toUIMessageStream pipeline, so the wire format can
// never drift from the SDK). The sibling use-chat-core.test.tsx mocks
// @ai-sdk/react entirely, which is exactly why the v7 onFinish rename shipped
// unseen: a callback the SDK no longer invokes is invisible under a mock.
//
// The contract under test: useChat's `onFinish` drives
// chatTurn.finishChatTurn for ALL THREE turn outcomes — normal completion,
// stop() mid-stream (isAbort), and a transport error (isError).
// ---------------------------------------------------------------------------

import type { UserProfile } from "@/lib/user/types"
import type { UIMessage } from "@ai-sdk/react"
import {
  createUIMessageStreamResponse,
  streamText,
  toUIMessageStream,
} from "ai"
import { MockLanguageModelV4, simulateReadableStream } from "ai/test"
import React, { act } from "react"
import { createRoot, type Root } from "react-dom/client"
import {
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from "vitest"
import type { useChatCore as UseChatCore } from "./use-chat-core"

let useChatCore: typeof UseChatCore

const seamMocks = vi.hoisted(() => ({
  convexMutation: vi.fn(),
  updateTitle: vi.fn(),
  // The observation point for the seam: the controller the hook's onFinish
  // must invoke. A singleton, so whichever render's closure fires, the same
  // spies record it.
  chatTurnController: {
    runSendTurn: vi.fn(async (_args: unknown) => {}),
    runSuggestionTurn: vi.fn(async (_args: unknown) => {}),
    runEditTurn: vi.fn(async (_args: unknown) => ({ status: "submitted" })),
    runRegenerationTurn: vi.fn(async (_args: unknown) => {}),
    finishChatTurn: vi.fn(async (_args: unknown) => {}),
  },
}))

// Only createChatTurnController (and types) are imported from this module in
// the hook's graph; a plain factory avoids loading the real controller chain.
vi.mock("@/lib/chat-turn/chat-turn-controller", () => ({
  createChatTurnController: () => seamMocks.chatTurnController,
}))

vi.mock("./turn-context", () => ({
  useTurnContext: () => ({
    selectedModel: "claude-haiku-4-5-20251001",
    handleModelChange: vi.fn(),
    enableSearch: false,
    setEnableSearch: vi.fn(),
    isAuthenticated: true,
    systemPrompt: "system prompt",
    isHydrated: true,
    getTurnSnapshot: () => ({
      selectedModel: "claude-haiku-4-5-20251001",
      systemPrompt: "system prompt",
      enableSearch: false,
      isAuthenticated: true,
      isHydrated: true,
    }),
  }),
}))

vi.mock("@/convex/_generated/api", () => ({
  api: {
    chatRuntime: {
      approveToolCall: "approveToolCall",
      denyToolCall: "denyToolCall",
    },
  },
}))

vi.mock("convex/react", () => ({
  useMutation: () => seamMocks.convexMutation,
  useConvex: () => ({}),
}))

vi.mock("next/navigation", () => ({
  useSearchParams: () => new URLSearchParams(window.location.search),
}))

vi.mock("@/components/ui/toast", () => ({
  toast: vi.fn(),
}))

vi.mock("@/lib/api", () => ({
  getOrCreateGuestUserId: vi.fn(async () => "user-1"),
}))

vi.mock("@/lib/chat-store/chats/provider", () => ({
  useChats: () => ({
    updateTitle: seamMocks.updateTitle,
  }),
}))

const CHAT_ID = "chat-seam"

const authenticatedUser = {
  id: "user-1",
  email: "user@example.com",
  display_name: "User",
  profile_image: null,
  anonymous: false,
  premium: true,
  message_count: 0,
  daily_message_count: 0,
  daily_reset: null,
  daily_pro_message_count: 0,
  daily_pro_reset: null,
  last_active_at: null,
  created_at: null,
  favorite_models: null,
  system_prompt: "system prompt",
} as unknown as UserProfile

const STEP_USAGE = {
  inputTokens: {
    total: 7,
    noCache: 7,
    cacheRead: undefined,
    cacheWrite: undefined,
  },
  outputTokens: { total: 3, text: 3, reasoning: undefined },
}

/**
 * Build a real v7 UI-message SSE Response by running the genuine server-side
 * pipeline over a mock provider model. `chunkDelayInMs` keeps the stream open
 * long enough for stop() to land mid-stream.
 */
function makeUiMessageSseResponse(options: {
  deltas: string[]
  chunkDelayInMs: number | null
}) {
  const result = streamText({
    model: new MockLanguageModelV4({
      doStream: async () => ({
        stream: simulateReadableStream({
          chunks: [
            { type: "stream-start" as const, warnings: [] },
            { type: "text-start" as const, id: "t1" },
            ...options.deltas.map((delta) => ({
              type: "text-delta" as const,
              id: "t1",
              delta,
            })),
            { type: "text-end" as const, id: "t1" },
            {
              type: "finish" as const,
              finishReason: { unified: "stop" as const, raw: "end_turn" },
              usage: STEP_USAGE,
            },
          ],
          chunkDelayInMs: options.chunkDelayInMs,
        }),
      }),
    }),
    prompt: "hi",
  })
  return createUIMessageStreamResponse({
    stream: toUIMessageStream({ stream: result.stream }),
  })
}

/**
 * Mirror real fetch abort semantics for the stubbed response: when the
 * transport's request signal aborts, the body reader must reject with an
 * AbortError — that is the signal path useChat's stop() relies on.
 */
function withAbortSemantics(
  response: Response,
  signal: AbortSignal | null | undefined
): Response {
  if (!signal || !response.body) return response
  const reader = response.body.getReader()
  const body = new ReadableStream<Uint8Array>({
    start(controller) {
      const onAbort = () => {
        controller.error(
          new DOMException("The operation was aborted.", "AbortError")
        )
        void reader.cancel().catch(() => {})
      }
      if (signal.aborted) onAbort()
      else signal.addEventListener("abort", onAbort, { once: true })
    },
    async pull(controller) {
      const { done, value } = await reader.read()
      if (done) controller.close()
      else controller.enqueue(value)
    },
    cancel() {
      void reader.cancel().catch(() => {})
    },
  })
  return new Response(body, {
    status: response.status,
    headers: response.headers,
  })
}

type HookApi = ReturnType<typeof UseChatCore>

describe("useChatCore × real @ai-sdk/react finalization", () => {
  let container: HTMLDivElement | null = null
  let root: Root | null = null
  const hookApiRef: { current: HookApi | null } = { current: null }
  const fetchMock = vi.fn<typeof fetch>()

  beforeAll(async () => {
    ;(
      globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }
    ).IS_REACT_ACT_ENVIRONMENT = true
    ;(
      globalThis as { requestAnimationFrame?: typeof requestAnimationFrame }
    ).requestAnimationFrame = (callback: FrameRequestCallback) =>
      window.setTimeout(() => callback(performance.now()), 0)
    // lib/chat-store/persist touches indexedDB at module scope — shim it
    // before the hook module (and its chat-store chain) loads.
    const objectStoreNames = Object.assign(["chats", "messages", "sync"], {
      contains: (name: string) => ["chats", "messages", "sync"].includes(name),
    })
    const db = {
      version: 2,
      objectStoreNames,
      close: vi.fn(),
      createObjectStore: vi.fn(),
    }
    ;(globalThis as { indexedDB?: IDBFactory }).indexedDB = {
      open: vi.fn(() => {
        const request = {
          result: db,
          error: null,
        } as unknown as IDBOpenDBRequest
        window.setTimeout(() => request.onsuccess?.(new Event("success")), 0)
        return request
      }),
      deleteDatabase: vi.fn(() => {
        const request = { result: undefined } as unknown as IDBOpenDBRequest
        window.setTimeout(() => request.onsuccess?.(new Event("success")), 0)
        return request
      }),
    } as unknown as IDBFactory
    ;({ useChatCore } = await import("./use-chat-core"))
  })

  beforeEach(() => {
    vi.clearAllMocks()
    vi.stubGlobal("fetch", fetchMock)
    window.history.replaceState(null, "", `/c/${CHAT_ID}`)
  })

  afterEach(() => {
    vi.unstubAllGlobals()
    const mountedRoot = root
    if (mountedRoot) {
      act(() => {
        mountedRoot.unmount()
      })
    }
    container?.remove()
    container = null
    root = null
    hookApiRef.current = null
  })

  function Harness() {
    const api = useChatCore({
      initialMessages: [] as UIMessage[],
      cacheAndAddMessage: vi.fn(),
      chatId: CHAT_ID,
      user: authenticatedUser,
      checkLimitsAndNotify: vi.fn(async () => true),
      ensureChatExists: vi.fn(async () => CHAT_ID),
      bumpChat: vi.fn(),
    })
    React.useEffect(() => {
      hookApiRef.current = api
    })
    return null
  }

  function renderHook(): HookApi {
    container = document.createElement("div")
    document.body.appendChild(container)
    root = createRoot(container)
    act(() => {
      root?.render(<Harness />)
    })
    const api = hookApiRef.current
    if (!api) throw new Error("useChatCore did not render")
    return api
  }

  /** Poll an assertion while flushing React work inside act(). */
  async function waitForInAct(assertion: () => void, timeoutMs = 4000) {
    const start = Date.now()
    for (;;) {
      try {
        assertion()
        return
      } catch (error) {
        if (Date.now() - start > timeoutMs) throw error
        await act(async () => {
          await new Promise((resolve) => setTimeout(resolve, 20))
        })
      }
    }
  }

  it("finishes a normal turn through finishChatTurn with clean flags", async () => {
    fetchMock.mockImplementation(async (_url, init) =>
      withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: ["Hello ", "world."],
          chunkDelayInMs: null,
        }),
        init?.signal
      )
    )
    const hook = renderHook()

    await act(async () => {
      await hook.sendMessage({ text: "hi" })
    })

    const finish = seamMocks.chatTurnController.finishChatTurn
    await waitForInAct(() => expect(finish).toHaveBeenCalledTimes(1))
    const args = finish.mock.calls[0][0] as Record<string, unknown>
    expect(args).toMatchObject({
      isAbort: false,
      isDisconnect: false,
      isError: false,
      chatId: CHAT_ID,
    })
    expect(args.finishReason).toBe("stop")
    const message = args.message as UIMessage
    expect(message.role).toBe("assistant")
    expect(
      message.parts
        .filter((part) => part.type === "text")
        .map((part) => (part as { text: string }).text)
        .join("")
    ).toBe("Hello world.")
  })

  it("finishes a stopped turn with isAbort after stop() mid-stream", async () => {
    fetchMock.mockImplementation(async (_url, init) =>
      withAbortSemantics(
        makeUiMessageSseResponse({
          deltas: Array.from({ length: 10 }, (_, i) => `piece-${i} `),
          chunkDelayInMs: 25,
        }),
        init?.signal
      )
    )
    const hook = renderHook()

    await act(async () => {
      void hook.sendMessage({ text: "hi" })
    })
    await waitForInAct(() =>
      expect(hookApiRef.current?.status).toBe("streaming")
    )

    await act(async () => {
      await hookApiRef.current?.stop()
    })

    const finish = seamMocks.chatTurnController.finishChatTurn
    await waitForInAct(() => expect(finish).toHaveBeenCalledTimes(1))
    expect(finish.mock.calls[0][0]).toMatchObject({
      isAbort: true,
      isError: false,
      chatId: CHAT_ID,
    })
  })

  it("finishes an errored turn with isError when the transport fails", async () => {
    fetchMock.mockImplementation(
      async () => new Response("model exploded", { status: 500 })
    )
    const hook = renderHook()

    await act(async () => {
      await hook.sendMessage({ text: "hi" })
    })

    const finish = seamMocks.chatTurnController.finishChatTurn
    await waitForInAct(() => expect(finish).toHaveBeenCalledTimes(1))
    expect(finish.mock.calls[0][0]).toMatchObject({
      isAbort: false,
      isError: true,
      chatId: CHAT_ID,
    })
    await waitForInAct(() => expect(hookApiRef.current?.status).toBe("error"))
  })
})
